# Defines the order in which to display Statistical Test documentation
# display_name: <h2>5.1 PD model replication</h2>

# Define the directory name where content files are saved  
dir_source: output

# Define order statistical tests/tasks will be integrated into documentation
dir_order:
  - 5_1_1_data_quality
  - 5_1_2_univariate_analysis
  - 5_1_3_model_coefficient_comparison
  - 5_1_4_score
  
# Define the content and order integrated into documentation
dir_details:
  5_1_1_data_quality:
#    display_name: <h2>5.1.1 Data quality</h2>
    file_order:
      - description.md
      - results.md
  5_1_2_univariate_analysis:
#    display_name: <h2>5.1.2 Univariate analysis</h2>
    file_order:
      - description.md
      - results.md
  5_1_3_model_coefficient_comparison:
#    display_name: <h2>5.1.3 Model coefficient comparison</h2>
    file_order:
      - description.md
      - results.md
  5_1_4_score:
    file_order:
      - description.md
      - results.md 